import assert from 'node:assert/strict';
import {AIController,normalize} from '../framework/ai.js';
import {TileMap} from '../framework/tilemap.js';
import {GridPathfinder} from '../framework/pathfinding.js';
import {Inventory} from '../framework/inventory.js';
import {QuestManager,QUEST_STATES} from '../framework/quests.js';
import {DialogueRunner} from '../framework/dialogue.js';
import {BossController} from '../framework/boss.js';
import {ArcadeVehicle} from '../framework/vehicle-physics.js';
import {SpriteSheet,SpriteAnimator} from '../framework/sprite-sheet.js';
import {SeededRandom,generateDungeon} from '../framework/procedural.js';
import {LoopbackTransport,MultiplayerSession} from '../framework/multiplayer.js';
import {LeaderboardClient, ENGINE_SYSTEMS, createEngineSystems} from '../framework/index.js';

const t=new TileMap({width:5,height:5,tileSize:10,solidIds:[1]});
t.addLayer('ground',[0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]);
assert.equal(t.solidAt(1,1),true);assert.deepEqual(t.worldToTile(24,14),{x:2,y:1});
const path=new GridPathfinder(t).find({x:0,y:0},{x:4,y:4}); assert.ok(path.length>0); assert.deepEqual(path[0],{x:0,y:0});
const ai=new AIController({x:0,y:0,speed:50}); ai.setTarget({x:100,y:0}); ai.setState('chase'); ai.update(.1); assert.ok(ai.position.x>0); assert.deepEqual(normalize({x:0,y:0}),{x:0,y:0});
const inv=new Inventory({capacity:2,maxStack:10}); assert.equal(inv.add('coin',5),0); assert.equal(inv.count('coin'),5); assert.equal(inv.remove('coin',2),2);assert.equal(inv.count('coin'),3);
const qm=new QuestManager([{id:'q',state:QUEST_STATES.ACTIVE,objectives:[{id:'x',target:2}]}]);qm.progress('q','x',2);assert.equal(qm.get('q').state,QUEST_STATES.COMPLETED);
const d=new DialogueRunner({start:'a',nodes:[{id:'a',lines:['hello'],next:'b'},{id:'b',lines:['bye']}]});assert.equal(d.currentLine(),'hello');assert.deepEqual(d.next(),{id:'b',lines:['bye']});assert.equal(d.currentLine(),'bye');
const boss=new BossController({maxHealth:100,phases:[{id:'p1',threshold:.5},{id:'p2',threshold:.2}]});boss.takeDamage(60);boss.update(.1);assert.equal(boss.phase.id,'p1');boss.takeDamage(80);assert.equal(boss.dead,true);
const car=new ArcadeVehicle({maxSpeed:100});car.control({throttle:1});car.update(.1);assert.ok(car.speed()>0);
const sheet=new SpriteSheet({frameWidth:16,frameHeight:16,columns:2,rows:2});assert.deepEqual(sheet.frame(3),{sx:16,sy:16,sw:16,sh:16});const anim=new SpriteAnimator({sheet,animations:{run:[0,1],idle:[2]},fps:10});anim.play('run');anim.update(.11);assert.equal(anim.index(),1);
const rng1=new SeededRandom('x'),rng2=new SeededRandom('x');assert.equal(rng1.next(),rng2.next());assert.equal(generateDungeon({width:12,height:8,seed:'x'}).cells.length,8);
const tr=new LoopbackTransport();const session=new MultiplayerSession({transport:tr});await session.connect();assert.equal(tr.opened,true);session.updateLocalState({hello:true});session.leave();
const storage={m:null,getItem(){return this.m},setItem(_k,v){this.m=v}};const lb=new LeaderboardClient({storage});await lb.submit({player:'A',score:15});await lb.submit({player:'B',score:40});assert.equal((await lb.get(2))[0].player,'B');
assert.ok(ENGINE_SYSTEMS.ai&&ENGINE_SYSTEMS.multiplayer&&typeof createEngineSystems().createBoss==='function');
console.log('ADVANCED_ENGINE_SYSTEMS_TESTS=PASS');
