import assert from 'node:assert/strict';
import {EventBus} from '../framework/events.js';
import {EntityManager} from '../framework/entities.js';
import {Camera2D} from '../framework/camera.js';
import {AssetManager} from '../framework/assets.js';
import {TimerManager} from '../framework/timers.js';
import {Scene,SceneManager} from '../framework/scene.js';
import {FixedStepper} from '../framework/fixed-step.js';
import {DebugMetrics} from '../framework/debug.js';
import {ErrorReporter} from '../framework/errors.js';
import {TweenManager} from '../framework/tween.js';
import {readFileSync} from 'node:fs';

const bus=new EventBus();let seen=0;bus.on('x',()=>seen++);bus.emit('x');assert.equal(seen,1);
const em=new EntityManager();let updated=0;const e={update(){updated++}};em.add(e);em.update(.016);assert.equal(updated,1);em.remove(e);assert.equal(em.size,0);
const cam=new Camera2D({viewportW:200,viewportH:100,worldW:500,worldH:300});cam.lookAt(250,150);const w=cam.screenToWorld(100,50);assert(Math.abs(w.x-250)<1e-9&&Math.abs(w.y-150)<1e-9);
const assets=new AssetManager();assert.equal(assets.has('image','x.png'),false);
const tm=new TimerManager();let fired=0;tm.after(.1,()=>fired++);tm.update(.11);assert.equal(fired,1);
const sm=new SceneManager();sm.add(new Scene('a'));sm.switch('a');assert.equal(sm.current.name,'a');
const step=new FixedStepper({step:.1,maxSteps:4});let steps=step.update(.25,()=>{});assert.equal(steps,2);
const metrics=new DebugMetrics();metrics.sample(.016);assert(metrics.frameTime>0);
const reporter=new ErrorReporter();reporter.capture(new Error('x'));assert.equal(reporter.count,1);reporter.clear();assert.equal(reporter.count,0);
const tweens=new TweenManager();const obj={x:0};tweens.to(obj,{x:10},1);tweens.update(.5);assert(obj.x>0&&obj.x<10);tweens.update(.5);assert.equal(obj.x,10);
const shellImport=readFileSync('framework/index.js','utf8');assert(!shellImport.includes('game-shell'));
const uiShell=readFileSync('ui/game-shell.js','utf8');assert(uiShell.includes("../framework/audio.js")&&uiShell.includes("../framework/core.js"));
const physics=readFileSync('framework/physics-2d.js','utf8');assert(physics.includes('Continuous axis sweeps') && physics.includes('function moveAndCollide'));
console.log('ENGINE_ARCHITECTURE_TEST_PASS');
import {Body2D,aabbOverlap,moveAndCollide} from '../framework/physics-2d.js';
import {SpatialHash} from '../framework/spatial-hash.js';
import {ObjectPool} from '../framework/object-pool.js';
import {InputMap} from '../framework/input-map.js';
import {defineConfig} from '../framework/game-config.js';
const body=new Body2D({x:0,y:0,w:10,h:10,gravity:0});const wall={x:20,y:0,w:10,h:20};body.vx=100;moveAndCollide(body,[wall],0.2);assert(body.x<=10);assert(aabbOverlap({left:0,right:10,top:0,bottom:10},{left:5,right:15,top:5,bottom:15}));
const hash=new SpatialHash(10),obj2={id:1};hash.insert(obj2,{x:2,y:2,w:4,h:4});assert.equal(hash.query({x:0,y:0,w:10,h:10})[0],obj2);hash.remove(obj2);assert.equal(hash.query({x:0,y:0,w:10,h:10}).length,0);
let created=0;const pool=new ObjectPool({create:()=>({n:++created}),reset:o=>{o.n=0},maxSize:2});const p=pool.acquire();pool.release(p);const p2=pool.acquire();assert.equal(p,p2);
const fake={down:(...keys)=>keys.includes('d'),pressed:()=>false};const map=new InputMap({right:['d'],left:['a']});assert.deepEqual(map.vector(fake),{x:1,y:0});
const build=defineConfig({speed:5,mode:'arcade'},{speed:{type:'number',min:1,max:10},mode:{oneOf:['arcade','physics']}});assert.equal(build({speed:20}).speed,10);
console.log('FOUNDATION_MODULES_TEST_PASS');
