export class Input {
  constructor(){this.keys=new Set();this.touch={left:false,right:false,up:false,down:false};this.mouse={active:false,x:0,y:0,down:false};this.pointerElement=null;this.touchPointerId=null;this.touchStart={x:0,y:0};this.touchThreshold=18;this.touchPulseTimer=null;
    this.onKeyDown=e=>{const k=String(e.key||'').toLowerCase(),c=String(e.code||'').toLowerCase();this.keys.add(k);this.keys.add(c);if(this.isControl(k,c))e.preventDefault()};
    this.onKeyUp=e=>{this.keys.delete(String(e.key||'').toLowerCase());this.keys.delete(String(e.code||'').toLowerCase())};this.onBlur=()=>this.clear();this.onVis=()=>{if(document.hidden)this.clear()};
    window.addEventListener('keydown',this.onKeyDown,{passive:false});window.addEventListener('keyup',this.onKeyUp);window.addEventListener('blur',this.onBlur);document.addEventListener('visibilitychange',this.onVis)}
  attachPointer(el,{mouse=true,touch=true}={}){if(!el)return;if(this.pointerElement)this.detachPointer();this.pointerElement=el;el.style.touchAction='none';
    this.downHandler=e=>{if(e.pointerType==='mouse'){if(mouse&&e.button===0){this.mouse.down=true;this.updateMouse(e)}return}if(!touch)return;this.touchPointerId=e.pointerId;this.touchStart={x:e.clientX,y:e.clientY};this.clearTouch();try{el.setPointerCapture(e.pointerId)}catch{}e.preventDefault()};
    this.moveHandler=e=>{if(e.pointerType==='mouse'){if(mouse)this.updateMouse(e);return}if(e.pointerId!==this.touchPointerId)return;const dx=e.clientX-this.touchStart.x,dy=e.clientY-this.touchStart.y;if(Math.hypot(dx,dy)<this.touchThreshold)return;this.pulse(Math.abs(dx)>=Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'));this.touchStart={x:e.clientX,y:e.clientY};e.preventDefault()};
    this.upHandler=e=>{if(e.pointerType==='mouse'){this.mouse.down=false;return}if(e.pointerId===this.touchPointerId)this.touchPointerId=null};this.cancelHandler=e=>{if(e.pointerType==='mouse')this.mouse.down=false;if(e.pointerId===this.touchPointerId)this.touchPointerId=null};
    el.addEventListener('pointerdown',this.downHandler,{passive:false});el.addEventListener('pointermove',this.moveHandler,{passive:false});el.addEventListener('pointerup',this.upHandler);el.addEventListener('pointercancel',this.cancelHandler);this.leaveHandler=()=>this.clearMouseTarget();el.addEventListener('pointerleave',this.leaveHandler)}
  detachPointer(){const e=this.pointerElement;if(!e)return;e.removeEventListener('pointerdown',this.downHandler);e.removeEventListener('pointermove',this.moveHandler);e.removeEventListener('pointerup',this.upHandler);e.removeEventListener('pointercancel',this.cancelHandler);e.removeEventListener('pointerleave',this.leaveHandler);this.pointerElement=null}
  updateMouse(e){const r=this.pointerElement?.getBoundingClientRect();if(!r)return;this.mouse.x=Math.max(0,Math.min(r.width,e.clientX-r.left));this.mouse.y=Math.max(0,Math.min(r.height,e.clientY-r.top));this.mouse.active=true}
  clearMouseTarget(){this.mouse.active=false;this.mouse.down=false}
  mousePosition(){return this.mouse.active?{x:this.mouse.x,y:this.mouse.y}:null} isMouseDown(){return this.mouse.down}
  vector(){const x=(this.right()?1:0)-(this.left()?1:0),y=(this.down()?1:0)-(this.up()?1:0),l=Math.hypot(x,y);return l?{x:x/l,y:y/l}:{x:0,y:0}} hasKeyboardMovement(){const v=this.vector();return !!(v.x||v.y)}
  pulse(d){this.clearTouch();this.touch[d]=true;clearTimeout(this.touchPulseTimer);this.touchPulseTimer=setTimeout(()=>this.clearTouch(),140)}
  isControl(k,c){return ['arrowleft','arrowright','arrowup','arrowdown','space','a','d','w','s','ص','ش','س','ي','p','ح','r','enter'].includes(k)||['keya','keyd','keyw','keys','arrowleft','arrowright','arrowup','arrowdown','space','keyp','keyr','enter'].includes(c)}
  isDown(...k){return k.some(x=>this.keys.has(String(x).toLowerCase()))}setTouch(d,v){if(d in this.touch)this.touch[d]=!!v}clearTouch(){Object.keys(this.touch).forEach(k=>this.touch[k]=false)}
  clear(){this.keys.clear();this.clearTouch();this.touchPointerId=null;this.mouse.down=false;clearTimeout(this.touchPulseTimer)}left(){return this.isDown('arrowleft','keya','a','ش')||this.touch.left}right(){return this.isDown('arrowright','keyd','d','ي')||this.touch.right}up(){return this.isDown('arrowup','keyw','w','ص')||this.touch.up}down(){return this.isDown('arrowdown','keys','s','س')||this.touch.down}
  destroy(){window.removeEventListener('keydown',this.onKeyDown);window.removeEventListener('keyup',this.onKeyUp);window.removeEventListener('blur',this.onBlur);document.removeEventListener('visibilitychange',this.onVis);this.detachPointer();this.clear()}}
